name: erbil
description: "Car rental"

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.5.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  get: ^4.6.6
  firebase_messaging: ^15.2.2
  cached_network_image: ^3.4.1

  firebase_core: ^3.11.0
  firebase_auth: ^5.4.2
  cloud_firestore: ^5.6.3
  firebase_storage: ^12.4.2
  firebase_pagination: ^4.1.0

  get_storage: ^2.1.1
  dio: ^5.8.0+1
  shimmer: ^3.0.0
  intl: ^0.20.1

  omni_datetime_picker: 2.0.5
  flutter_inappwebview: ^6.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
