// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC5Gt9j-MiaFRZFPrrzubANMthwtWhfnUA',
    appId: '1:436707362957:web:3f100c7f4f5c366324bac4',
    messagingSenderId: '436707362957',
    projectId: 'erbil-comma',
    authDomain: 'erbil-comma.firebaseapp.com',
    storageBucket: 'erbil-comma.firebasestorage.app',
    measurementId: 'G-CJY101YR3T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCcx3kCxaRMoicUgbTKzUAxSWVQlKuOWFA',
    appId: '1:436707362957:android:333a4b94f08079f924bac4',
    messagingSenderId: '436707362957',
    projectId: 'erbil-comma',
    storageBucket: 'erbil-comma.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD_Np37fyY5u1dIQGIYd55V4OkQaHM39Ns',
    appId: '1:436707362957:ios:bfaba7233e3bf9a524bac4',
    messagingSenderId: '436707362957',
    projectId: 'erbil-comma',
    storageBucket: 'erbil-comma.firebasestorage.app',
    iosClientId: '436707362957-pv2gdt6la8n23ujuqvl823qist5onrmm.apps.googleusercontent.com',
    iosBundleId: 'com.commatech.erbil',
  );
}
